spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf8&useSSL=false
    username: root
    password: QAQm..02r
mybatis-plus:
  configuration:
#    设置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
#      设置实体类所对应的表的统一前缀
      table-prefix: t_
#      设置统一的主键的生成策略
      id-type: auto
#      配置类型别名
  type-aliases-package: com.doromv.pojo
#      扫描通用枚举的包
  type-enums-package: com.doromv.enums

